import type { LucideIcon, LucideIconData } from '@lucide/angular';
import {
  LucideArrowRight,
  LucideBuilding2,
  LucideCheck,
  LucideCircleCheck,
  LucideChevronLeft,
  LucideChevronRight,
  LucideMaximize2,
  LucideCirclePlus,
  LucideCircleX,
  LucideCode2,
  LucideDatabase,
  LucideDownload,
  LucideExternalLink,
  LucideGitBranch,
  LucideGitFork,
  LucideGlobe,
  LucideHouse,
  LucideImagePlus,
  LucideInfo,
  LucideLayers,
  LucideListFilter,
  LucideLock,
  LucideMail,
  LucideMenu,
  LucideMoon,
  LucidePalette,
  LucideScale,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShieldCheck,
  LucideSquarePen,
  LucideStar,
  LucideSun,
  LucideUser,
  LucideX,
  LucideSend,
  LucideFolderInput,
  LucideLayoutPanelTop,
  LucideMessagesSquare,
  LucideSparkles,
} from '@lucide/angular';
type PortfolioLucideIcon = LucideIcon | LucideIconData;

const toLucideIconData = (icon: PortfolioLucideIcon): LucideIconData => ('icon' in icon ? icon.icon : icon);

const PortfolioLucideIcons = {
  Add: LucideCirclePlus,
  ArrowRight: LucideArrowRight,
  Check: LucideCheck,
  CheckCircle: LucideCircleCheck,
  ChevronLeft: LucideChevronLeft,
  ChevronRight: LucideChevronRight,
  Expand: LucideMaximize2,
  Close: LucideX,
  CloseCircle: LucideCircleX,
  Code: LucideCode2,
  Company: LucideBuilding2,
  Database: LucideDatabase,
  Download: LucideDownload,
  Edit: LucideSquarePen,
  Email: LucideMail,
  ExternalLink: LucideExternalLink,
  Filter: LucideListFilter,
  Folder: LucideFolderInput,
  Github: LucideGitBranch,
  GitFork: LucideGitFork,
  Globe: LucideGlobe,
  Home: LucideHouse,
  Image: LucideImagePlus,
  Info: LucideInfo,
  Layers: LucideLayers,
  License: LucideScale,
  Lock: LucideLock,
  MediaPreview: LucideLayoutPanelTop,
  Menu: LucideMenu,
  MessagesSquare: LucideMessagesSquare,
  Moon: LucideMoon,
  Palette: LucidePalette,
  Search: LucideSearch,
  Send: LucideSend,
  Server: LucideServer,
  Settings: LucideSettings,
  ShieldCheck: LucideShieldCheck,
  Sparkles: LucideSparkles,
  Star: LucideStar,
  Sun: LucideSun,
  User: LucideUser,
} as const satisfies Record<string, PortfolioLucideIcon>;

export const LucideIcons = Object.fromEntries(Object.entries(PortfolioLucideIcons).map(([name, icon]) => [name, toLucideIconData(icon)])) as { [Name in keyof typeof PortfolioLucideIcons]: LucideIconData };

export type LucideIconName = keyof typeof LucideIcons;
