import type { LucideIcon, LucideIconData } from '@lucide/angular';
import {
  LucideArrowRight,
  LucideBell,
  LucideBuilding2,
  LucideChevronDown,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleChevronDown,
  LucideCircleChevronUp,
  LucideCirclePlus,
  LucideCircleX,
  LucideClipboardList,
  LucideCode2,
  LucideDatabase,
  LucideDownload,
  LucideEllipsisVertical,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideFileUser,
  LucideFolderInput,
  LucideGitBranch,
  LucideGlobe,
  LucideHouse,
  LucideImagePlus,
  LucideInbox,
  LucideInfo,
  LucideLayers,
  LucideLayoutPanelTop,
  LucideLink2,
  LucideLock,
  LucideLogOut,
  LucideMail,
  LucideMenu,
  LucideMessagesSquare,
  LucideMoon,
  LucidePalette,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePaperclip,
  LucidePhone,
  LucidePhoneIncoming,
  LucidePhoneMissed,
  LucidePhoneOutgoing,
  LucideSearch,
  LucideSend,
  LucideSendHorizontal,
  LucideServer,
  LucideSettings,
  LucideShieldCheck,
  LucideSmile,
  LucideSquarePen,
  LucideSun,
  LucideUser,
  LucideVideo,
  LucideVoicemail,
  LucideVolume2,
  LucideWaypoints,
  LucideX,
} from '@lucide/angular';

type PortfolioLucideIcon = LucideIcon | LucideIconData;

const toLucideIconData = (icon: PortfolioLucideIcon): LucideIconData => ('icon' in icon ? icon.icon : icon);

const PortfolioLucideIcons = {
  Add: LucideCirclePlus,
  ArrowRight: LucideArrowRight,
  Bell: LucideBell,
  CallIncoming: LucidePhoneIncoming,
  CallMissed: LucidePhoneMissed,
  CallOutgoing: LucidePhoneOutgoing,
  ChevronCircleDown: LucideCircleChevronDown,
  ChevronCircleUp: LucideCircleChevronUp,
  ChevronDown: LucideChevronDown,
  ChevronRight: LucideChevronRight,
  ChevronUp: LucideChevronUp,
  CloseCircle: LucideCircleX,
  Close: LucideX,
  Code: LucideCode2,
  Company: LucideBuilding2,
  ComposerSend: LucideSendHorizontal,
  Database: LucideDatabase,
  Download: LucideDownload,
  Edit: LucideSquarePen,
  Ellipsis: LucideEllipsisVertical,
  Email: LucideMail,
  Emoji: LucideSmile,
  ExternalLink: LucideExternalLink,
  Eye: LucideEye,
  EyeOff: LucideEyeOff,
  FileLink: LucideLink2,
  Folder: LucideFolderInput,
  Github: LucideGitBranch,
  Globe: LucideGlobe,
  Home: LucideHouse,
  IdCard: LucideFileUser,
  Image: LucideImagePlus,
  Inbox: LucideInbox,
  Info: LucideInfo,
  Information: LucideFileText,
  Layers: LucideLayers,
  Linkedin: LucideLink2,
  Lock: LucideLock,
  LogOut: LucideLogOut,
  MediaPreview: LucideLayoutPanelTop,
  Menu: LucideMenu,
  MessagesSquare: LucideMessagesSquare,
  Moon: LucideMoon,
  Palette: LucidePalette,
  PanelClose: LucidePanelLeftClose,
  PanelOpen: LucidePanelLeftOpen,
  Paperclip: LucidePaperclip,
  Phone: LucidePhone,
  PointsEmission: LucideWaypoints,
  Search: LucideSearch,
  Send: LucideSend,
  Server: LucideServer,
  Settings: LucideSettings,
  ShieldCheck: LucideShieldCheck,
  SignOut: LucideLogOut,
  Sun: LucideSun,
  User: LucideUser,
  Video: LucideVideo,
  Voicemail: LucideVoicemail,
  Volume2: LucideVolume2,
  WorkOrders: LucideClipboardList,
} as const satisfies Record<string, PortfolioLucideIcon>;

export const LucideIcons = Object.fromEntries(
  Object.entries(PortfolioLucideIcons).map(([name, icon]) => [name, toLucideIconData(icon)]),
) as { [Name in keyof typeof PortfolioLucideIcons]: LucideIconData };

export type LucideIconName = keyof typeof LucideIcons;
